swagger: '2.0'
info:
  description: This is the API documentation for the COP 4331 Penguin Book App
  version: '1.0.0'
  title: PenguinBook
paths:
  /Login.php:
    post:
      summary: 'Authenticate User'
      description: 'Endpoint to Login a user.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'loginItem'
          description: 'User login credentials'
          required: true
          schema:
            $ref: '#/definitions/Login'
      responses:
        200:
          description: 'Successfully authenticated'
          schema:
            $ref: '#/definitions/UserResponse'
        400:
          description: 'Bad Request - Invalid input'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        401:
          description: 'Unauthorized - Invalid login credentials'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        500:
          description: 'Internal Server Error'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'

  /Register.php:
    post:
      summary: 'Register User'
      description: 'Endpoint to register a new user.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'userItem'
          description: 'User registration details'
          required: true
          schema:
            $ref: '#/definitions/Register'
      responses:
        200:
          description: 'User registered successfully'
          schema:
            type: 'object'
            properties:
              message:
                type: 'string'
        400:
          description: 'Bad Request - Invalid input or missing required fields'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        409:
          description: 'Conflict - Login already exists'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        500:
          description: 'Internal Server Error'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'

  /DeleteContact.php:
    post:
      summary: 'Delete Contact'
      description: 'Endpoint to delete a contact.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'deleteItem'
          description: 'Contact details for deletion'
          required: true
          schema:
            $ref: '#/definitions/DeleteContact'
      responses:
        200:
          description: 'Contact deleted successfully'
          schema:
            type: 'object'
            properties:
              message:
                type: 'string'
        400:
          description: 'Bad Request - Invalid input or missing required fields'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        404:
          description: 'Not Found - Contact not found or no changes made'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        500:
          description: 'Internal Server Error'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'

  /AddContact.php:
    post:
      summary: 'Add Contact'
      description: 'Endpoint to add a new contact.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'contactItem'
          description: 'Contact details for addition'
          required: true
          schema:
            $ref: '#/definitions/AddContact'
      responses:
        200:
          description: 'Contact added successfully'
          schema:
            type: 'object'
            properties:
              message:
                type: 'string'
        400:
          description: 'Bad Request - Invalid input or missing required fields'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        500:
          description: 'Internal Server Error'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'

  /UpdateContact.php:
    post:
      summary: 'Update Contact'
      description: 'Endpoint to update an existing contact.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'contactItem'
          description: 'Contact details for update'
          required: true
          schema:
            $ref: '#/definitions/UpdateContact'
      responses:
        200:
          description: 'Contact updated successfully'
          schema:
            type: 'object'
            properties:
              message:
                type: 'string'
        400:
          description: 'Bad Request - Invalid input or no changes made'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        404:
          description: 'Not Found - Contact not found'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        500:
          description: 'Internal Server Error'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'

  /SearchContact.php:
    post:
      summary: 'Search Contacts'
      description: 'Endpoint to search contacts based on user ID, first name, and last name.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'searchItem'
          description: 'Contact Search'
          required: true
          schema:
            $ref: '#/definitions/SearchContact'
      responses:
        200:
          description: 'Contacts found successfully'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Contact'
        400:
          description: 'Bad Request - Invalid input or no contacts found'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'
        500:
          description: 'Internal Server Error'
          schema:
            type: 'object'
            properties:
              error:
                type: 'string'

definitions:
  Login:
    type: 'object'
    required:
      - login
      - password
    properties:
      login:
        type: 'string'
      password:
        type: 'string'

  Register:
    type: 'object'
    required:
      - login
      - password
      - firstName
      - lastName
    properties:
      login:
        type: 'string'
      password:
        type: 'string'
      firstName:
        type: 'string'
      lastName:
        type: 'string'

  DeleteContact:
    type: 'object'
    required:
      - userId
      - firstName
      - lastName
    properties:
      userId:
        type: 'integer'
        format: 'int64'
      firstName:
        type: 'string'
      lastName:
        type: 'string'

  UserResponse:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      firstName:
        type: 'string'
      lastName:
        type: 'string'
      error:
        type: 'string'

  AddContact:
    type: 'object'
    required:
      - firstName
      - lastName
      - phone
      - email
      - userId
    properties:
      firstName:
        type: 'string'
      lastName:
        type: 'string'
      phone:
        type: 'string'
      email:
        type: 'string'
      userId:
        type: 'integer'
        format: 'int64'

  UpdateContact:
    type: 'object'
    required:
      - contactId
    properties:
      contactId:
        type: 'integer'
        format: 'int64'
      firstName:
        type: 'string'
      lastName:
        type: 'string'

  SearchContact:
    type: 'object'
    required:
      - userId
    properties:
      userId:
        type: 'integer'
        format: 'int64'
      firstName:
        type: 'string'
      lastName:
        type: 'string'

  Contact:
    type: 'object'
    properties:
      ID:
        type: 'integer'
        format: 'int64'
      FirstName:
        type: 'string'
      LastName:
        type: 'string'
      Phone:
        type: 'string'
      Email:
        type: 'string'
      UserID:
        type: 'integer'
        format: 'int64'

host: penguinbook.xyz
basePath: /LAMPAPI
schemes:
- http